# Server Configuration
server:
  host: 0.0.0.0
  port: 8080
  environment: development
  debug: true
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

# Database Configuration
database:
  primary:
    driver: mongodb
    uri: mongodb://localhost:27017
    database_name: myappdb
    username: appuser
    password: secretpassword
    
    # Connection pool and timeout settings
    min_pool_size: 10
    max_pool_size: 100
    max_connection_timeout: 30s
    max_idle_time: 5m

# Logging Configuration
logging:
  level: info
  format: json
  output_paths: ./var/log/myapp/app.log

# Cache Configuration
cache:
  default:
    type: redis
    host: localhost
    port: 6379
    database: 0
    password: cachesecret
    pool_size: 10
    min_idle_connections: 5

# External Services
external_services:
  auth_service:
    url: https://auth.example.com
    timeout: 10s
    api_key: service_api_key_here

  payment_gateway:
    provider: stripe
    api_key: stripe_secret_key
    webhook_secret: webhook_signing_secret

# Feature Flags
features:
  user_registration: true
  advanced_analytics: false

# Security Configuration
security:
  jwt:
    secret_key: your_jwt_secret_here
    token_duration: 24h
    issuer: myapp.com

  cors:
    allowed_origins:
      - https://app.example.com
      - http://localhost:3000
    allowed_methods:
      - GET
      - POST
      - PUT
      - DELETE
    allowed_headers:
      - Authorization
      - Content-Type

# Application-Specific Configuration
app:
  name: MyAwesomeApp
  version: 1.2.3
  contact_email: support@myapp.com
  support_url: https://support.myapp.com
  description: "A simple product catalog API"
  base_url: "/api/v1"
  log_level: "info"